# Generated by Django 4.2.25 on 2025-10-11 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_message_edited_messagehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messaging_recived_messages',
            new_name='messaging_receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_replies', to='messaging.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
