# Generated by Django 4.2.25 on 2025-10-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_rename_messaging_recived_messages_message_messaging_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='context',
            new_name='content',
        ),
    ]
