version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db 
      DB_PORT: 3306 
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
    volumes:
      - mysql_data:/var/lib/mysql 


volumes:
    mysql_data:
      driver : local
  