#!/bin/bash

BLUE_DEPLOYMENT="django-blue"
GREEN_DEPLOYMENT="django-green"
SERVICE_NAME="django-app-service"


echo "Applying MySQL, Blue (v1.0), Green (v2.0) Deployments, and Service..."
kubectl apply -f mysql-deployment.yaml
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml
kubectl apply -f kubeservice.yaml


if [ $? -ne 0 ]; then
    echo "ERROR: Failed to apply Kubernetes configuration files."
    exit 1
fi


echo "Waiting for Green Deployment (v2.0) Pods to become ready..."

kubectl rollout status deployment/$GREEN_DEPLOYMENT --timeout=5m

if [ $? -ne 0 ]; then
    echo "ERROR: Green deployment failed to become ready. Aborting deployment."
    exit 1
fi

echo "Green Deployment (v2.0) is fully ready and running alongside Blue (v1.0)."

echo "logs of the new Green Pods for common errors"


GREEN_POD=$(kubectl get pods -l app=django-app,version=v2.0 -o jsonpath='{.items[0].metadata.name}')

if [ -z "$GREEN_POD" ]; then
    echo "ERROR: Could not find a running Green Pod for log check. Aborting."
    exit 1
fi


LOGS=$(kubectl logs $GREEN_POD --tail=20 2>&1)
echo "$LOGS"
if echo "$LOGS" | grep -E "OperationalError|FATAL|Traceback|Error|exception"; then
    echo "--------------------------------------------------------"
    echo "❌ CRITICAL ERROR DETECTED IN GREEN DEPLOYMENT LOGS."
    echo "Deployment halted. Traffic remains on Blue (v1.0)."
    echo "--------------------------------------------------------"
    exit 1
fi

echo "Log check passed. No critical errors detected in the Green Pod ($GREEN_POD)."


echo "Rraffic switch from v1.0 (Blue) to v2.0 (Green)..."


kubectl patch service $SERVICE_NAME -p '{"spec": {"selector": {"app": "django-app", "version": "v2.0"}}}'

if [ $? -eq 0 ]; then
    echo "--------------------------------------------------------"
    echo "SUCCESS: Traffic is now routed to GREEN (v2.0)."
    echo "The Blue-Green deployment is complete. Blue (v1.0) can be scaled down."
    echo "--------------------------------------------------------"
else
    echo "❌ FAILURE: Service patch failed. Traffic remains on BLUE (v1.0)."
    exit 1
fi

echo "--- Current Service Selector ---"
kubectl describe service $SERVICE_NAME | grep Selector
